highlighter: pygments
markdown: kramdown
exclude: ['node_modules','gruntfile.js','package.json','README.md','Vagrantfile','Gemfile','Gemfile.lock']

collections:
  projects:
    output: true
    permalink: /project/:path/