highlighter: pygments
markdown: kramdown
exclude: ['node_modules','gruntfile.js','package.json','README.md','Vagrantfile','Gemfile','Gemfile.lock']
baseurl: /ckirkham.github.io

repository: https://github.com/ckirkham/ckirkham.github.io

collections:
  projects:
    output: true